require 'socket'
require 'securerandom'
require 'json'
require 'etc'
require 'readline'
require 'tempfile'
require 'open3'

require './communication/packet'
require './communication/message'
require './communication/connection'
require './client'
require './application'
